postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: password
  PostgresqlDbname: database

http_server:
  port: 8080

services:
  auth:
    addr: 127.0.0.1:3999
  tweets:
    addr: 127.0.0.1:3998

rabbitmq:
  username: vercello
  password: vercello
  host: localhost
  port: 5672
  exchangeName: tweets-exchange
  queueName: tweets-queue
  consumerTag: tweets-consumer
  bindingKey: tweets-routing-key


metrics:
  jaeger:
    endpoint: http://localhost:14268/api/traces

app:
  jwt:
    secret: yata_auth_key
    token_ttl_hours: 12
    salt: yata_vercello_salt


mode: dev
